# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ddev < Formula
  desc "DDEV"
  homepage "https://github.com/drud/ddev"
  version "1.19.4-alpha1"
  license "Apache 2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/drud/ddev/releases/download/v1.19.4-alpha1/ddev_macos-amd64.v1.19.4-alpha1.tar.gz"
      sha256 "212d144306b50d8dbbca28d596d8fcf09fcc97bffab7da2d55f1ea7d6788e5ff"

      def install
        if build.head?
            os = OS.mac? ? "darwin" : "linux"
            arch = Hardware::CPU.arm? ? "arm64" : "amd64"
            system "mkdir", "-p", "#{bin}"
            system "make", "VERSION=v#{version}", "COMMIT=v#{version}"
            system "cp", ".gotmp/bin/" + os + "_" + arch + "/ddev", "#{bin}/ddev"
        else
            bin.install "ddev"
            bash_completion.install "ddev_bash_completion.sh" => "ddev"
            zsh_completion.install "ddev_zsh_completion.sh" => "ddev"
            fish_completion.install "ddev_fish_completion.sh" => "ddev"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/drud/ddev/releases/download/v1.19.4-alpha1/ddev_macos-arm64.v1.19.4-alpha1.tar.gz"
      sha256 "a6e9fdaab9777d76ece88fae0b1dcc4cd26cc4e23b9ae30a50b757ea2dcde290"

      def install
        if build.head?
            os = OS.mac? ? "darwin" : "linux"
            arch = Hardware::CPU.arm? ? "arm64" : "amd64"
            system "mkdir", "-p", "#{bin}"
            system "make", "VERSION=v#{version}", "COMMIT=v#{version}"
            system "cp", ".gotmp/bin/" + os + "_" + arch + "/ddev", "#{bin}/ddev"
        else
            bin.install "ddev"
            bash_completion.install "ddev_bash_completion.sh" => "ddev"
            zsh_completion.install "ddev_zsh_completion.sh" => "ddev"
            fish_completion.install "ddev_fish_completion.sh" => "ddev"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drud/ddev/releases/download/v1.19.4-alpha1/ddev_linux-arm64.v1.19.4-alpha1.tar.gz"
      sha256 "f13f234aab83979d247bf593fd16cb15b425ff00f24891a54cefcb372208316c"

      def install
        if build.head?
            os = OS.mac? ? "darwin" : "linux"
            arch = Hardware::CPU.arm? ? "arm64" : "amd64"
            system "mkdir", "-p", "#{bin}"
            system "make", "VERSION=v#{version}", "COMMIT=v#{version}"
            system "cp", ".gotmp/bin/" + os + "_" + arch + "/ddev", "#{bin}/ddev"
        else
            bin.install "ddev"
            bash_completion.install "ddev_bash_completion.sh" => "ddev"
            zsh_completion.install "ddev_zsh_completion.sh" => "ddev"
            fish_completion.install "ddev_fish_completion.sh" => "ddev"
        end
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/drud/ddev/releases/download/v1.19.4-alpha1/ddev_linux-amd64.v1.19.4-alpha1.tar.gz"
      sha256 "a97b39c4292d9a5d853a49a8bbd4734327fa4e9ca619d64c2658c3b3a99ed5ae"

      def install
        if build.head?
            os = OS.mac? ? "darwin" : "linux"
            arch = Hardware::CPU.arm? ? "arm64" : "amd64"
            system "mkdir", "-p", "#{bin}"
            system "make", "VERSION=v#{version}", "COMMIT=v#{version}"
            system "cp", ".gotmp/bin/" + os + "_" + arch + "/ddev", "#{bin}/ddev"
        else
            bin.install "ddev"
            bash_completion.install "ddev_bash_completion.sh" => "ddev"
            zsh_completion.install "ddev_zsh_completion.sh" => "ddev"
            fish_completion.install "ddev_fish_completion.sh" => "ddev"
        end
      end
    end
  end

  head "https://github.com/drud/ddev.git", branch: "master"
  depends_on "go" => :build
  depends_on "make" => :build

  depends_on "mkcert"

  test do
    system "#{bin}/ddev --version"
  end
end
